### ISSUE TITLE
Question: Pagination

### ISSUE THREAD

**Issue by odrobnik** [kasperisager/vanilla-api#72]
When querying `categories` how does pagination work? I found that if I directly access the JSON page on the form, every request I get a new page.... 

Is there a way to determine how many pages there are and to get a specific page by passing a parameter to the API?

**Comment by kasperisager** [comment]
Most controllers expose some sort a pagination parameters, and some APIs shim these in order to allow passing them in request bodies (e.g. https://github.com/kasperisager/vanilla-api/blob/master/library/apis/class.discussionsapi.php#L28). You'd have to take a look through the corresponding controller to see what parameters it exposes; feel free to throw me a line if you find some that might benefit from a shim.
